### ISSUE TITLE
Dependencies installation

### ISSUE THREAD

**Issue by WolkeWS** [semenko/serpent-methylation-pipeline#1]
The optional 4th installation step does not work without a name for the environment in the env.yaml file (see https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file)

**Comment by WolkeWS** [comment]
Also missing bedtools dependency

**Comment by semenko** [comment]
Thanks! Updating shortly.
